### ISSUE TITLE
Addons don't work in 1.15.2 paperspigot

### ISSUE THREAD

**Issue by Teyir** [BentoBoxWorld/Border#17]
Hello, I have install the Border addons in BSkyBlock 1.15.2 paperspigot but when I install that addons he don't work, I have this error in my console →
 ``>.... [10:40:09 WARN]: [BentoBox] Skipping Border as it is incompatible with the current version of BentoBox or of server software...
>.... [10:40:09 WARN]: [BentoBox] NOTE: The addon is referring to no longer existing classes.
>.... [10:40:09 WARN]: [BentoBox] NOTE: DO NOT report this as a bug from BentoBox.
>.... [10:40:09 ERROR]: [BentoBox] Please report this stack trace to the addon's author(s): [tastybento]
java.lang.NoClassDefFoundError: com/github/yannicklamprecht/worldborder/api/BorderAPI
at world.bentobox.border.Border.onEnable(Border.java:73) ~[?:?]
at world.bentobox.bentobox.managers.AddonsManager.enableAddon(AddonsManager.java:177) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_212]
at world.bentobox.bentobox.managers.AddonsManager.enableAddons(AddonsManager.java:156) ~[?:?]
at world.bentobox.bentobox.BentoBox.lambda$onEnable$2(BentoBox.java:177) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-89]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(Min``

Thank you very much for the help

**Comment by BONNe** [comment]
@tastybento, you should catch this exception and just write simpler message.
For Border addon you need WorldBorderAPI as it is mentioned in Border addon repository
